/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_Janus_Janus */

#ifndef _Included_com_example_Janus_Janus
#define _Included_com_example_Janus_Janus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_Janus_Janus
 * Method:    printData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_Janus_Janus_printData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
