/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Janus_Janus */

#ifndef _Included_Janus_Janus
#define _Included_Janus_Janus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Janus_Janus
 * Method:    PrintData
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Janus_Janus_PrintData
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
