/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class plugins_quorum_Libraries_Game_Graphics_Models_Printing_Slicer */

#ifndef _Included_plugins_quorum_Libraries_Game_Graphics_Models_Printing_Slicer
#define _Included_plugins_quorum_Libraries_Game_Graphics_Models_Printing_Slicer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     plugins_quorum_Libraries_Game_Graphics_Models_Printing_Slicer
 * Method:    Slice
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_plugins_quorum_Libraries_Game_Graphics_Models_Printing_Slicer_Slice
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
